### PR TITLE
fixed static generate with nuxt 1.4

### PR DESCRIPTION
**Pull request by apmontgomery**
This should fix the static generate errors and routing issues. :)

### CODE REVIEW

**Comment by joostdecock** [comment]
Hmm, I still have broken client-side routing. Specifically:

First I had an error about the route generation. I assumed you used pulled in the [nuxtent-example](https://github.com/joostdecock/nuxtent-example) code before I added the generation of dynamic routes to the config.

Removing that config snippet got rid of the error, which I guess means two things:

 - It shows that yarn correctly linked the module with your latest changes
 - Dynamic routes (for markdown content) are added without the need for config mucking about, which is great

Another improvement is that `yarn build` + `yarn start` does work, including correct client-side routing (that wasn't the case earlier, client side routing was broken).

However, it seems that client-side routing is still broken on `yarn generate`. As in, it creates all the pages correcty, and thus I can pick any valid link to enter the site. But then it drops in SPA mode and the routing doesn't work. It still tries to contact the content-api.

Perhaps I'm misunderstanding something, or perhaps there's something I did to nuxt-example to break it. Or perhaps it's progress, but not a complete fix.

Your thoughts?

**Comment by apmontgomery** [comment]
when you run yarn generate, does it say: 

`nuxt:axios BaseURL: http://localhost:3000/content-api (Browser: /_nuxt/content) +0ms`

or does it say

`nuxt:axios BaseURL: http://localhost:3000/content-api (Browser: /content-api) +0ms`

?

**Comment by joostdecock** [comment]
It says:

```
  nuxt:axios BaseURL: http://localhost:3000/content-api (Browser: http://localhost:3000/_nuxt/content) 
```

Full output:

```
yarn generate
yarn run v1.5.1
$ nuxt generate
  nuxt:generate Generating... +0ms
  nuxt: Call build:before hooks (1) +0ms
starting build nuxtent
  nuxt:axios BaseURL: http://localhost:3000/content-api (Browser: http://localhost:3000/_nuxt/content) +0ms
  nuxt:build App root: /my/git/bangkok/bounty2/nuxtent-example +0ms
  nuxt:build Generating /my/git/bangkok/bounty2/nuxtent-example/.nuxt files... +0ms
  nuxt:build Generating files... +60ms
  nuxt:build Generating routes... +10ms
  nuxt:build Building files... +27ms
  ████████████████████ 100% 

Build completed in 11.85s



 DONE  Compiled successfully in 11855ms                                                                                                                                                                     16:34:15

Hash: 6c29ce8fa584a7d9f2c0
Version: webpack 3.11.0
Time: 11855ms
                                        Asset       Size  Chunks             Chunk Names
        content/blog.calling-all-patrons.json    9.45 kB          [emitted]  
          pages/index.b69e76429adf7238b283.js    3.46 kB       0  [emitted]  pages/index
     pages/blog/index.e71c76ef669837cbdb9c.js    1.11 kB       2  [emitted]  pages/blog/index
     pages/blog/_post.b5aa2e6364ca1b305f88.js    1.15 kB       3  [emitted]  pages/blog/_post
               vendor.65de81d62f64dc616a9e.js     159 kB       4  [emitted]  vendor
                  app.e04c9b9b7d63da686e49.js    32.8 kB       5  [emitted]  app
             manifest.6c29ce8fa584a7d9f2c0.js    1.56 kB       6  [emitted]  manifest
                                     LICENSES  705 bytes          [emitted]  
            content/blog.roundup-2018-02.json     5.5 kB          [emitted]  
          content/blog.core-vim-snippets.json    2.62 kB          [emitted]  
                  content/blog.gdpr-plan.json    19.7 kB          [emitted]  
            content/blog.roundup-2018-01.json    7.15 kB          [emitted]  
         content/blog.announcing-carlita.json    4.86 kB          [emitted]  
           content/blog.introducing-bail.json    8.57 kB          [emitted]  
         content/blog.core-v1-3-0-is-out.json    5.58 kB          [emitted]  
            content/blog.roundup-2017-12.json    9.63 kB          [emitted]  
content/blog.announcing-carlton-and-bent.json    5.86 kB          [emitted]  
      layouts/default.70db92a20ce50714d4bd.js    1.42 kB       1  [emitted]  layouts/default
      content/blog.florent-flat-cap-beta.json    2.44 kB          [emitted]  
            content/blog.roundup-2017-11.json    8.43 kB          [emitted]  
      content/blog.benjamin-bow-tie-beta.json    2.94 kB          [emitted]  
            content/blog.roundup-2017-10.json     5.4 kB          [emitted]  
           content/blog.huey-hoodie-beta.json       3 kB          [emitted]  
               content/blog.where-are-we.json    7.35 kB          [emitted]  
            content/blog.roundup-2017-09.json    8.27 kB          [emitted]  
    content/blog.freesewing-from-scratch.json    37.5 kB          [emitted]  
        content/blog.email-spam-problems.json    7.76 kB          [emitted]  
      content/blog.the-refashioners-2017.json    11.4 kB          [emitted]  
          content/blog.open-for-business.json    12.9 kB          [emitted]  
         content/blog.core-v1-1-1-is-out.json    7.16 kB          [emitted]  
            content/blog.announcing-sven.json    1.31 kB          [emitted]  
            content/blog.privacy-choices.json    5.02 kB          [emitted]  
   content/blog.freesewing-goes-jamstack.json    7.88 kB          [emitted]  
      content/blog.announcing-freesewing.json    4.42 kB          [emitted]  
                            content/_all.json     213 kB          [emitted]  
 + 3 hidden assets
Hash: b2d4308eede885e20b6e
Version: webpack 3.11.0
Time: 786ms
             Asset    Size  Chunks             Chunk Names
server-bundle.json  143 kB          [emitted]  
  nuxt: Call build:done hooks (1) +14s
opening server connection
  nuxt: Call generate:distRemoved hooks (1) +20ms
  nuxt:generate Destination folder cleaned +14s
  nuxt: Call generate:distCopied hooks (1) +14ms
  nuxt:generate Static & build files copied +15ms
  nuxt:render Rendering url /blog +0ms
  nuxt:render Rendering url / +37ms
  nuxt:render Rendering url /blog/roundup-2018-02 +2ms
  nuxt:render Rendering url /blog/core-vim-snippets +1ms
  nuxt:render Rendering url /blog/gdpr-plan +0ms
  nuxt:render Rendering url /blog/roundup-2018-01 +0ms
  nuxt:render Rendering url /blog/announcing-carlita +0ms
  nuxt:render Rendering url /blog/introducing-bail +0ms
  nuxt:render Rendering url /blog/core-v1-3-0-is-out +1ms
  nuxt:render Rendering url /blog/roundup-2017-12 +0ms
  nuxt:render Rendering url /blog/announcing-carlton-and-bent +0ms
  nuxt:render Rendering url /blog/calling-all-patrons +0ms
  nuxt:render Rendering url /blog/florent-flat-cap-beta +0ms
  nuxt:render Rendering url /blog/roundup-2017-11 +1ms
  nuxt:render Rendering url /blog/benjamin-bow-tie-beta +0ms
  nuxt:render Rendering url /blog/roundup-2017-10 +0ms
  nuxt:render Rendering url /blog/huey-hoodie-beta +0ms
  nuxt:render Rendering url /blog/where-are-we +0ms
  nuxt:render Rendering url /blog/roundup-2017-09 +0ms
  nuxt:render Rendering url /blog/freesewing-from-scratch +1ms
  nuxt:render Rendering url /blog/email-spam-problems +0ms
  nuxt:render Rendering url /blog/the-refashioners-2017 +0ms
  nuxt:render Rendering url /blog/open-for-business +0ms
  nuxt:render Rendering url /blog/core-v1-1-1-is-out +0ms
  nuxt:render Rendering url /blog/announcing-sven +0ms
  nuxt:render Rendering url /blog/privacy-choices +1ms
  nuxt:render Rendering url /blog/freesewing-goes-jamstack +0ms
  nuxt:render Rendering url /blog/announcing-freesewing +0ms
  nuxt: Call generate:page hooks (1) +211ms
  nuxt:generate Generate file: /index.html +210ms
/content-api GET http://localhost:3000/
	Response sent successfully.
/content-api GET http://localhost:3000/blog/roundup-2018-02
	Response sent successfully.
/content-api GET http://localhost:3000/blog/core-vim-snippets
	Response sent successfully.
/content-api GET http://localhost:3000/blog/gdpr-plan
	Response sent successfully.
/content-api GET http://localhost:3000/blog/roundup-2018-01
	Response sent successfully.
/content-api GET http://localhost:3000/blog/announcing-carlita
	Response sent successfully.
/content-api GET http://localhost:3000/blog/introducing-bail
	Response sent successfully.
/content-api GET http://localhost:3000/blog/core-v1-3-0-is-out
	Response sent successfully.
/content-api GET http://localhost:3000/blog/roundup-2017-12
	Response sent successfully.
/content-api GET http://localhost:3000/blog/announcing-carlton-and-bent
	Response sent successfully.
/content-api GET http://localhost:3000/blog/calling-all-patrons
	Response sent successfully.
/content-api GET http://localhost:3000/blog/florent-flat-cap-beta
	Response sent successfully.
/content-api GET http://localhost:3000/blog/roundup-2017-11
	Response sent successfully.
/content-api GET http://localhost:3000/blog/benjamin-bow-tie-beta
	Response sent successfully.
/content-api GET http://localhost:3000/blog/roundup-2017-10
	Response sent successfully.
/content-api GET http://localhost:3000/blog/huey-hoodie-beta
	Response sent successfully.
/content-api GET http://localhost:3000/blog/where-are-we
	Response sent successfully.
/content-api GET http://localhost:3000/blog/roundup-2017-09
	Response sent successfully.
/content-api GET http://localhost:3000/blog/freesewing-from-scratch
	Response sent successfully.
/content-api GET http://localhost:3000/blog/email-spam-problems
	Response sent successfully.
/content-api GET http://localhost:3000/blog/the-refashioners-2017
	Response sent successfully.
/content-api GET http://localhost:3000/blog/open-for-business
	Response sent successfully.
/content-api GET http://localhost:3000/blog/core-v1-1-1-is-out
	Response sent successfully.
/content-api GET http://localhost:3000/blog/announcing-sven
	Response sent successfully.
/content-api GET http://localhost:3000/blog/privacy-choices
	Response sent successfully.
/content-api GET http://localhost:3000/blog/freesewing-goes-jamstack
	Response sent successfully.
/content-api GET http://localhost:3000/blog/announcing-freesewing
	Response sent successfully.
  nuxt: Call generate:page hooks (1) +529ms
  nuxt:generate Generate file: /blog/index.html +529ms
  nuxt: Call generate:page hooks (1) +34ms
  nuxt:generate Generate file: /blog/roundup-2018-02/index.html +34ms
  nuxt: Call generate:page hooks (1) +25ms
  nuxt:generate Generate file: /blog/core-vim-snippets/index.html +25ms
  nuxt: Call generate:page hooks (1) +38ms
  nuxt:generate Generate file: /blog/gdpr-plan/index.html +38ms
  nuxt: Call generate:page hooks (1) +23ms
  nuxt:generate Generate file: /blog/roundup-2018-01/index.html +23ms
  nuxt: Call generate:page hooks (1) +24ms
  nuxt:generate Generate file: /blog/announcing-carlita/index.html +24ms
  nuxt: Call generate:page hooks (1) +31ms
  nuxt:generate Generate file: /blog/introducing-bail/index.html +31ms
  nuxt: Call generate:page hooks (1) +24ms
  nuxt:generate Generate file: /blog/core-v1-3-0-is-out/index.html +24ms
  nuxt: Call generate:page hooks (1) +28ms
  nuxt:generate Generate file: /blog/roundup-2017-12/index.html +28ms
  nuxt: Call generate:page hooks (1) +25ms
  nuxt:generate Generate file: /blog/announcing-carlton-and-bent/index.html +26ms
  nuxt: Call generate:page hooks (1) +33ms
  nuxt:generate Generate file: /blog/calling-all-patrons/index.html +32ms
  nuxt: Call generate:page hooks (1) +17ms
  nuxt:generate Generate file: /blog/florent-flat-cap-beta/index.html +17ms
  nuxt: Call generate:page hooks (1) +25ms
  nuxt:generate Generate file: /blog/roundup-2017-11/index.html +25ms
  nuxt: Call generate:page hooks (1) +19ms
  nuxt:generate Generate file: /blog/benjamin-bow-tie-beta/index.html +19ms
  nuxt: Call generate:page hooks (1) +23ms
  nuxt:generate Generate file: /blog/roundup-2017-10/index.html +23ms
  nuxt: Call generate:page hooks (1) +26ms
  nuxt:generate Generate file: /blog/huey-hoodie-beta/index.html +26ms
  nuxt: Call generate:page hooks (1) +25ms
  nuxt:generate Generate file: /blog/where-are-we/index.html +25ms
  nuxt: Call generate:page hooks (1) +23ms
  nuxt:generate Generate file: /blog/roundup-2017-09/index.html +23ms
  nuxt: Call generate:page hooks (1) +66ms
  nuxt:generate Generate file: /blog/freesewing-from-scratch/index.html +66ms
  nuxt: Call generate:page hooks (1) +19ms
  nuxt:generate Generate file: /blog/email-spam-problems/index.html +19ms
  nuxt: Call generate:page hooks (1) +22ms
  nuxt:generate Generate file: /blog/the-refashioners-2017/index.html +22ms
  nuxt: Call generate:page hooks (1) +31ms
  nuxt:generate Generate file: /blog/open-for-business/index.html +32ms
  nuxt: Call generate:page hooks (1) +20ms
  nuxt:generate Generate file: /blog/core-v1-1-1-is-out/index.html +20ms
  nuxt: Call generate:page hooks (1) +14ms
  nuxt:generate Generate file: /blog/announcing-sven/index.html +14ms
  nuxt: Call generate:page hooks (1) +19ms
  nuxt:generate Generate file: /blog/privacy-choices/index.html +18ms
  nuxt: Call generate:page hooks (1) +19ms
  nuxt:generate Generate file: /blog/freesewing-goes-jamstack/index.html +23ms
  nuxt: Call generate:page hooks (1) +23ms
  nuxt:generate Generate file: /blog/announcing-freesewing/index.html +19ms
  nuxt:render Rendering url / +1s
  nuxt: Call generate:done hooks (2) +10ms
  nuxt:generate HTML Files generated in 15.4s +10ms
closing server connection
  nuxt:generate Generate done +1ms
Done in 16.94s.
```

**Comment by apmontgomery** [comment]
screen shot 2018-03-22 at 5 34 01 pm

**Comment by joostdecock** [comment]
Hmm, let me rebuild the entire thing from scratch.

Meanwhile, what commit of `nuxtent-example` are you on?

**Comment by apmontgomery** [comment]
I am about to run off to dinner, but I'm happy to help work this out with you.  Your output looks correct to me.

**Comment by joostdecock** [comment]
ok, I'll see what I can learn from my side

**Comment by apmontgomery** [comment]
I'm on 
```
commit 360a8daae42b1ca628a3a12c67a8c39d34eea3a1
Merge: 19281fc 953ba6b
Author: Joost <joost@decock.org>
Date:   Wed Mar 21 14:31:51 2018 +0700

    Merge pull request #2 from icarito/fix_generate

    Point api to port 3000
```

**Comment by apmontgomery** [comment]
I'll pull your latest

**Comment by joostdecock** [comment]
I think I found out what the difference is. It's an issue with the `baseURL` option in the nuxtent.config.js file.

After generating the site, I want to dump the `dist` folder in the webroot of a web server and have it *just work*.

It doesn't, because it assumes it's getting its content from `http://localhost:3000`.

I noticed in your screenshot that you are running the site at localhost:3000, so that's why it works for you.

I am running a (different) webserver on localhost:8080 that has the `dist` folder as webroot. The content requests go to `http://localhost:3000/_nuxt....` so obviously that doesn't work.

Question: how do we get the baseURL to take the domain:port of the site, and only muck with the path?

**Comment by joostdecock** [comment]
screenshot from 2018-03-22 16-57-41

Screenshot to clarify: Note the different port number for the requests in the `domain` column.

**Comment by joostdecock** [comment]
ok, so we just need to get the thing to target a different URL during build, and in the browser.  
After combing through the docs, it turns out that's trivial:

```
   api: {
     baseURL: 'http://localhost:3000',
     browserBaseURL: 'http://localhost:8080'
   }
```

This snippet in `nuxtent.config.js` does the trick, and `yarn generate` now works when served from a dumb static webhost :)

I'll let you confirm before getting too excited

**Comment by apmontgomery** [comment]
Try this:

api: function(isStatic) {
    return {
      sbrowserBaseURL: isStatic ? ‘localhost:3000’ : ‘localhost:8080’
    }

**Comment by apmontgomery** [comment]
Or yours works better

**Comment by apmontgomery** [comment]
Sorry for the typos. On my phone now. I’ll run everything when I get home

**Comment by joostdecock** [comment]
Relax, I think we've got it sorted out 🙂

I'll communicate this upstream, enjoy your dinner in the meanwhile.

**Comment by apmontgomery** [comment]
Just back home and tested with the baseURL/ browserBaseURL config setup.  It looks like everything is working well. I'm glad we could get this worked out and I really appreciate you putting the bounty up. :)

**Comment by joostdecock** [comment]
About that. I'll need your email address for a PayPal transaction. You can contact me at joost `at` decock `dot` org

**Pull request merged**
